### ISSUE TITLE
Grimoire Gun "Focussed Shot"

### ISSUE THREAD

**Issue by Vaialyss** [grimoireofheart/grimoireofheart.github.io#7]
Not sure if it's intentional or not, but on the chance it's a typo:

In the Grimoire Gun PDF, the spell Focused Shot reads, "Focussed Shot."

**Comment by grimoireofheart** [comment]
"Grimoire Gun" is Heartverse content, and not handled by the Core Grimoire team. Please inform the author, CamBAM (TDZ)#0179.
